/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package suzume;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class App {
    
    public static void main(String[] args) {
        // ...
    }
}
