/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package suzume;

import java.util.ArrayList;
import java.util.List;

public class App {
    
    public static void main(String[] args) {
        final int testCase = 10;

        for (int i = 0; i < testCase; ++i) {
            List<Player> pList = new ArrayList<>();
            
            for (int p = 1; p < 5; ++p) {
                pList.add(Player.of(("P" + p), ("Player" + p)));
            }

            SuzumeSession session = SuzumeSession.makeSession("testSession", pList);

            // SuzumeSession.calcHuaryoScore();
        }
    }
}
